name: Deploy to GCP VM (Reusable)

on:
  workflow_call:
    inputs:
      target_directory:
        required: true
        type: string
    secrets:
      gcp_vm_host:
        required: true
      gcp_vm_username:
        required: true
      gcp_vm_private_key:
        required: true 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy files to GCP VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          source: "."
          target: ${{ inputs.target_directory }}

      - name: Restart Apache2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2 
