name: CI

on:
  push:
    branches:
      - main

jobs:
  call-build-and-push:
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      branches: '["main"]'
      image_names: '["html-test"]'
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
