name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
      image_names:
        required: true
        type: string
      dockerhub_username:
        required: true
        type: string
      dockerhub_password:
        required: true
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        image_name: ${{ inputs.image_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io # Optional, good practice to be explicit
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_password }}

      - name: Build Docker image
        run: docker build -t ${{ inputs.dockerhub_username }}/${{ matrix.image_name }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ inputs.dockerhub_username }}/${{ matrix.image_name }}:latest

# name: Build and Push Docker Image

# on:
#   workflow_call:

# jobs:
#   build_and_push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
    
#     strategy:
#       matrix:
#         image_name: ["html-test", "my-other-image"] # Define multiple image names if needed

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           registry: docker.io # Optional, good practice to be explicit
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Build Docker image
#         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest .

#       - name: Push Docker image to Docker Hub
#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest


# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build: 
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Build Docker image
#         run: |
#           docker build -t my-docker-repo:latest .
#           docker tag my-docker-repo:latest ${{ secrets.DOCKERHUB_USERNAME }}/html-test:latest

#       - name: Push Docker image to Docker Hub
#         run: |
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/html-test:latest
