name: Deploy to GCP VM

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secrets for debugging
        run: |
           echo "${{ secrets.GCP_VM_HOST }}"
           echo "${{ secrets.GCP_VM_USERNAME }}"
           echo "${{ secrets.GCP_VM_PRIVATE_KEY }}"

      - name: Copy files to GCP VM
        uses: appleboy/scp-action@master 
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          source: "."  
          target: "/var/www/html/html-test"  # Target directory on GCP VM
