name: Custom Message
on:
  push:
    branches:
      - gchat-msg

jobs:
  gChat_Notification:
    uses: ankushjha-aj/Send-notification-to-gChat-if-SSL-renewal-and-deployment-fail/.github/workflows/gchat_notification.yaml@standard-Workflow
    secrets:
      GCHAT_URL: ${{ secrets.GCHAT_URL }}
    with:
      MESSAGE: "Calling this workflow from another Verify That we can Send messages accordingly if we don't have any SSL renewal Notification To send"
  
