name: Reusable workflow 
on:
  workflow_call: 
  
jobs: 
  run-job-1: 
  
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: write something to log
         run: |
           echo "I'm Reusable-Workflow from HTML repo "
